from ..graph import LAYER_COLORS


def generate_markdown(analysis, G, metrics, filepath="ARCHITECTURE.md"):
    lines = []
    lines.append("# Architecture Overview")
    lines.append("")
    lines.append(f"_Generated by [Archiscape](https://github.com/NullLabTests/archiscape) v0.1.0_")
    lines.append("")
    lines.append(f"- **Project:** `{analysis.get('project_root', 'unknown')}`")
    lines.append(f"- **Components:** {metrics.get('num_nodes', 0)}")
    lines.append(f"- **Dependencies:** {metrics.get('num_edges', 0)}")
    lines.append(f"- **Graph density:** {metrics.get('density', 0):.3f}")
    lines.append(f"- **Communities detected:** {metrics.get('num_communities', 0)}")
    lines.append(f"- **Connected components:** {metrics.get('num_components', 0)}")
    lines.append("")

    layers = metrics.get("layers", {})
    if layers:
        lines.append("## Layer Distribution")
        lines.append("")
        lines.append("| Layer | Components | Proportion |")
        lines.append("|-------|-----------|------------|")
        total = max(sum(layers.values()), 1)
        for layer, count in sorted(layers.items(), key=lambda x: -x[1]):
            pct = f"{100 * count / total:.0f}%"
            lines.append(f"| {layer.capitalize()} | {count} | {pct} |")
        lines.append("")

    fan_in = metrics.get("avg_fan_in")
    fan_out = metrics.get("avg_fan_out")
    if fan_in is not None:
        lines.append("## Coupling Metrics")
        lines.append("")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Average fan-in (afferent coupling) | {fan_in} |")
        lines.append(f"| Maximum fan-in | {metrics.get('max_fan_in', 0)} |")
        lines.append(f"| Average fan-out (efferent coupling) | {fan_out} |")
        lines.append(f"| Maximum fan-out | {metrics.get('max_fan_out', 0)} |")
        lines.append("")

    hubs = metrics.get("hubs", [])
    if hubs:
        lines.append("## Central Components (Hubs)")
        lines.append("")
        lines.append("| Component | Degree | Fan-in | Fan-out | Layer |")
        lines.append("|-----------|--------|--------|---------|-------|")
        for h in hubs[:10]:
            lines.append(f"| {h['name']} | {h['degree']} | {h['fan_in']} | {h['fan_out']} | {h['layer']} |")
        lines.append("")

    lines.append("## Module Inventory")
    lines.append("")
    lines.append("<details>")
    lines.append("<summary>Expand full component tree</summary>")
    lines.append("")
    for mod in analysis.get("entities", []):
        _render_module(lines, mod, G, 0)
    lines.append("")
    lines.append("</details>")

    content = "\n".join(lines)
    if filepath:
        with open(filepath, "w") as f:
            f.write(content)
    return content


def _render_module(lines, entity, G, depth):
    indent = "  " * depth
    kind = entity["kind"]
    if kind == "module":
        prefix = "📦 "
    elif kind == "class":
        prefix = "  └ 🏛 "
    else:
        prefix = "    └ 🔧 "
    name = entity.get("full_name", entity["name"])
    doc = entity.get("docstring")

    parts = [name]
    if G and G.has_node(name):
        nd = G.nodes[name]
        layer = nd.get("layer", "other")
        if layer != "other":
            parts.append(f"*{layer}*")
    line = f"{indent}{prefix}{' — '.join(parts)}"
    if doc:
        line += f" — {doc[:100]}"
    lines.append(line)

    for child in entity.get("children", []):
        _render_module(lines, child, G, depth + 1)
