def generate_markdown(analysis, G, metrics, filepath="ARCHITECTURE.md"):
    lines = []
    lines.append("# Architecture Overview")
    lines.append("")
    lines.append(f"_Generated by Archiscape v0.1.0_")
    lines.append("")
    lines.append(f"**Project:** {analysis.get('project_root', 'unknown')}")
    lines.append(f"**Modules analyzed:** {metrics.get('num_nodes', 0)}")
    lines.append(f"**Dependencies:** {metrics.get('num_edges', 0)}")
    lines.append(f"**Architectural layers detected:** {len(metrics.get('layers', {}))}")
    lines.append("")

    layers = metrics.get("layers", {})
    if layers:
        lines.append("## Layer Distribution")
        lines.append("")
        lines.append("| Layer | Components |")
        lines.append("|-------|-----------|")
        for layer, count in sorted(layers.items(), key=lambda x: -x[1]):
            lines.append(f"| {layer.capitalize()} | {count} |")
        lines.append("")

    lines.append("## Module Inventory")
    lines.append("")
    for mod in analysis.get("entities", []):
        _render_module(lines, mod, G, 0)

    content = "\n".join(lines)
    if filepath:
        with open(filepath, "w") as f:
            f.write(content)
    return content


def _render_module(lines, entity, G, depth):
    indent = "  " * depth
    prefix = "📦 " if entity["kind"] == "module" else "🏛️ " if entity["kind"] == "class" else "🔧 "
    name = entity.get("full_name", entity["name"])

    doc = entity.get("docstring")
    doc_str = f": {doc}" if doc else ""

    lines.append(f"{indent}{prefix}**{name}**{doc_str}")

    if G and G.has_node(name):
        node_data = G.nodes[name]
        layer = node_data.get("layer", "other")
        if layer != "other":
            lines.append(f"{indent}  _Layer: {layer}_")

        imports = node_data.get("imports", [])
        if imports:
            ext = [i["name"] for i in imports if i.get("kind") == "external"]
            if ext:
                lines.append(f"{indent}  _Ext deps: {', '.join(ext[:5])}{'...' if len(ext) > 5 else ''}_")

    for child in entity.get("children", []):
        _render_module(lines, child, G, depth + 1)
