import json
from collections import defaultdict


def _graphml_clean(val):
    if val is None:
        return ""
    if isinstance(val, (bool, int, float)):
        return val
    if isinstance(val, (list, dict)):
        return json.dumps(val)
    return str(val)


def export_graphml(G, filepath="architecture.graphml"):
    nx = _get_networkx()
    if nx is None:
        return ""

    H = nx.DiGraph()
    for n, data in G.nodes(data=True):
        clean = {k: _graphml_clean(v) for k, v in data.items()}
        H.add_node(n, **clean)
    for u, v, data in G.edges(data=True):
        clean = {k: _graphml_clean(v) for k, v in data.items()}
        H.add_edge(u, v, **clean)

    nx.write_graphml(H, filepath)
    return filepath


def export_mermaid(G, filepath="architecture.mmd"):
    lines = []
    lines.append("graph TD")
    lines.append("")

    for n, data in G.nodes(data=True):
        kind = data.get("kind", "unknown")
        layer = data.get("layer", "other")
        label = data.get("name", n)
        if kind == "module":
            node_id = _mermaid_id(n)
            lines.append(f"    {node_id}[{label}]")
            lines.append(f"    style {node_id} fill:{_layer_fill(layer)},stroke:{_layer_stroke(layer)}")
        elif kind == "class":
            node_id = _mermaid_id(n)
            name_short = label.split(".")[-1]
            doc = data.get("docstring", "")
            if doc:
                name_short += f"<br/><i>{doc[:60]}</i>"
            lines.append(f"    {node_id}({name_short})")
        elif kind == "function":
            node_id = _mermaid_id(n)
            name_short = label.split(".")[-1]
            lines.append(f"    {node_id}[{name_short}]")

    edges_added = set()
    for u, v, data in G.edges(data=True):
        rel = data.get("relation", "depends")
        edge_key = (u, v, rel)
        if edge_key in edges_added:
            continue
        edges_added.add(edge_key)
        uid = _mermaid_id(u)
        vid = _mermaid_id(v)
        if rel == "contains":
            lines.append(f"    {uid} -.-> {vid}")
        else:
            lines.append(f"    {uid} --> {vid}")

    content = "\n".join(lines)
    if filepath:
        with open(filepath, "w") as f:
            f.write(content)
    return content


def export_markdown_architecture_report(analysis, G, metrics, smells, filepath="architecture_report.md"):
    lines = []
    lines.append("# Architecture Analysis Report")
    lines.append("")
    lines.append(f"_Generated by Archiscape_")
    lines.append("")
    lines.append("## Overview")
    lines.append("")
    lines.append(f"- **Project:** {analysis.get('project_root', 'unknown')}")
    lines.append(f"- **Components:** {metrics.get('num_nodes', 0)}")
    lines.append(f"- **Dependencies:** {metrics.get('num_edges', 0)}")
    lines.append(f"- **Communities:** {metrics.get('num_communities', 0)}")
    lines.append(f"- **Graph Density:** {metrics.get('density', 0):.4f}")
    lines.append("")

    if smells:
        lines.append("## Architecture Smells")
        lines.append("")
        lines.append("| Type | Component | Score | Message |")
        lines.append("|------|-----------|-------|---------|")
        for s in smells[:15]:
            lines.append(f"| {s['type']} | `{s['component'][:60]}` | {s['score']} | {s['message']} |")
        lines.append("")

    layers = metrics.get("layers", {})
    if layers:
        lines.append("## Layer Distribution")
        lines.append("")
        lines.append("| Layer | Count | % |")
        lines.append("|-------|-------|---|")
        total = max(sum(layers.values()), 1)
        for layer, count in sorted(layers.items(), key=lambda x: -x[1]):
            pct = f"{100 * count / total:.0f}"
            lines.append(f"| {layer} | {count} | {pct}% |")
        lines.append("")

    hubs = metrics.get("hubs", [])
    if hubs:
        lines.append("## Top Hubs")
        lines.append("")
        lines.append("| Component | Degree | Fan-in | Fan-out | Layer |")
        lines.append("|-----------|--------|--------|---------|-------|")
        for h in hubs[:8]:
            lines.append(f"| {h['name']} | {h['degree']} | {h['fan_in']} | {h['fan_out']} | {h['layer']} |")
        lines.append("")

    lines.append("## Dependency Graph (Mermaid)")
    lines.append("")
    lines.append("```mermaid")
    mermaid_content = export_mermaid(G, filepath=None)
    lines.append(mermaid_content)
    lines.append("```")
    lines.append("")

    content = "\n".join(lines)
    if filepath:
        with open(filepath, "w") as f:
            f.write(content)
    return content


def _get_networkx():
    try:
        import networkx as nx
        return nx
    except ImportError:
        return None


def _mermaid_id(name):
    safe = name.replace(".", "_").replace("-", "_").replace("/", "_")
    safe = "".join(c for c in safe if c.isalnum() or c == "_")
    if safe and safe[0].isalpha():
        return safe
    return "n" + safe


_LAYER_FILLS = {
    "presentation": "#ffcccc",
    "application": "#ffe0b2",
    "domain": "#c8e6c9",
    "infrastructure": "#bbdefb",
    "analysis": "#e1bee7",
    "rendering": "#f8bbd0",
    "config": "#d7ccc8",
    "utility": "#d7ccc8",
    "other": "#f5f5f5",
}

_LAYER_STROKES = {
    "presentation": "#b71c1c",
    "application": "#e65100",
    "domain": "#1b5e20",
    "infrastructure": "#0d47a1",
    "analysis": "#4a148c",
    "rendering": "#880e4f",
    "config": "#4e342e",
    "utility": "#4e342e",
    "other": "#616161",
}


def _layer_fill(layer):
    return _LAYER_FILLS.get(layer, "#f5f5f5")


def _layer_stroke(layer):
    return _LAYER_STROKES.get(layer, "#616161")
